"""Versioned boundary records (master architecture ch. 20). Each record is closed, immutable,
float-free and coercion-free for identity-bearing scalars; see `_base.py`."""

from sindri.schemas.candidate import (
    CandidateFile,
    CandidateManifest,
    ModelAuthor,
    ProducerRole,
    candidate_source_hash,
)
from sindri.schemas.cross_record import InvariantCode, Violation, check_records
from sindri.schemas.episode import (
    ACTIVE_EPISODE_STATES,
    ALLOWED_EPISODE_TRANSITIONS,
    CANDIDATE_REQUIRED_STATES,
    TERMINAL_EPISODE_STATES,
    AbortReason,
    BudgetRemaining,
    BudgetVector,
    CandidateBinding,
    EpisodeBudget,
    EpisodeState,
    EpisodeStatus,
    PendingJob,
)

# Finding's ProducerRole shares its class name with CandidateManifest's, so it is exported as
# FindingProducerRole (P1.1-G B5: found by the A3 public-API inventory).
from sindri.schemas.finding import (
    ALLOWED_FINDING_TRANSITIONS,
    ComponentProducer,
    CycleWindow,
    DevelopmentProbeRequest,
    DropReason,
    ExistingPolicyCheck,
    Finding,
    FindingStatus,
    FindingTransition,
    HumanProducer,
    ModelProducer,
    ObservationCitation,
    SupportingArtifact,
    SupportingArtifactKind,
    Uncertainty,
)
from sindri.schemas.finding import ProducerRole as FindingProducerRole
from sindri.schemas.observation import (
    ACTION_FOR_KIND,
    Diagnostic,
    DiagnosticCategory,
    EquivalenceReport,
    EvidenceKind,
    EvidenceRef,
    FormalReport,
    Observation,
    ObservationAction,
    PropertyResult,
    Severity,
    SimulationReport,
    StructuralReport,
    TestResult,
    observation_execution_key,
)
from sindri.schemas.policy import (
    Check,
    CheckKind,
    Configuration,
    EnvironmentAssumption,
    EvaluationPolicy,
    ExcludedPair,
    FormalMode,
    Obligation,
    ParameterAssignment,
    PolicyException,
    Visibility,
)
from sindri.schemas.requirement import (
    AllSupportedConfigs,
    Assumption,
    EnvironmentRule,
    ParameterScope,
    ParameterValues,
    Requirement,
    RequirementDisposition,
)
from sindri.schemas.task import (
    READ_ONLY_TASK_TYPES,
    GeneratorSource,
    MutationSource,
    RepoSource,
    SourceRights,
    Split,
    TaskManifest,
    TaskType,
    UseCaseSource,
)

__all__ = [
    "ACTION_FOR_KIND",
    "ACTIVE_EPISODE_STATES",
    "ALLOWED_EPISODE_TRANSITIONS",
    "ALLOWED_FINDING_TRANSITIONS",
    "AbortReason",
    "AllSupportedConfigs",
    "Assumption",
    "BudgetRemaining",
    "BudgetVector",
    "CANDIDATE_REQUIRED_STATES",
    "CandidateBinding",
    "CandidateFile",
    "CandidateManifest",
    "Check",
    "CheckKind",
    "ComponentProducer",
    "Configuration",
    "CycleWindow",
    "DevelopmentProbeRequest",
    "Diagnostic",
    "DiagnosticCategory",
    "DropReason",
    "EnvironmentAssumption",
    "EnvironmentRule",
    "EpisodeBudget",
    "EpisodeState",
    "EpisodeStatus",
    "EquivalenceReport",
    "EvaluationPolicy",
    "EvidenceKind",
    "EvidenceRef",
    "ExcludedPair",
    "ExistingPolicyCheck",
    "Finding",
    "FindingStatus",
    "FindingProducerRole",
    "FindingTransition",
    "FormalMode",
    "FormalReport",
    "GeneratorSource",
    "HumanProducer",
    "InvariantCode",
    "ModelAuthor",
    "ModelProducer",
    "MutationSource",
    "Obligation",
    "Observation",
    "ObservationAction",
    "ObservationCitation",
    "ParameterAssignment",
    "ParameterScope",
    "ParameterValues",
    "PendingJob",
    "PolicyException",
    "ProducerRole",
    "PropertyResult",
    "READ_ONLY_TASK_TYPES",
    "RepoSource",
    "Requirement",
    "RequirementDisposition",
    "Severity",
    "SimulationReport",
    "SourceRights",
    "Split",
    "StructuralReport",
    "SupportingArtifact",
    "SupportingArtifactKind",
    "TERMINAL_EPISODE_STATES",
    "TaskManifest",
    "TaskType",
    "TestResult",
    "Uncertainty",
    "UseCaseSource",
    "Violation",
    "Visibility",
    "candidate_source_hash",
    "check_records",
    "observation_execution_key",
]
