"""Versioned boundary records (master architecture ch. 20). Each record is closed, immutable,
float-free and coercion-free for identity-bearing scalars; see `_base.py`."""

from sindri.schemas.candidate import (
    CandidateFile,
    CandidateManifest,
    ModelAuthor,
    ProducerRole,
    candidate_source_hash,
)
from sindri.schemas.policy import (
    Check,
    CheckKind,
    Configuration,
    EnvironmentAssumption,
    EvaluationPolicy,
    ExcludedPair,
    FormalMode,
    Obligation,
    ParameterAssignment,
    PolicyException,
    Visibility,
)
from sindri.schemas.requirement import (
    AllSupportedConfigs,
    Assumption,
    EnvironmentRule,
    ParameterScope,
    ParameterValues,
    Requirement,
    RequirementDisposition,
)
from sindri.schemas.task import (
    READ_ONLY_TASK_TYPES,
    GeneratorSource,
    MutationSource,
    RepoSource,
    SourceRights,
    Split,
    TaskManifest,
    TaskType,
    UseCaseSource,
)

__all__ = [
    "AllSupportedConfigs",
    "Assumption",
    "CandidateFile",
    "CandidateManifest",
    "Check",
    "CheckKind",
    "Configuration",
    "EnvironmentAssumption",
    "EnvironmentRule",
    "EvaluationPolicy",
    "ExcludedPair",
    "FormalMode",
    "GeneratorSource",
    "ModelAuthor",
    "MutationSource",
    "Obligation",
    "ParameterAssignment",
    "ParameterScope",
    "ParameterValues",
    "PolicyException",
    "ProducerRole",
    "READ_ONLY_TASK_TYPES",
    "RepoSource",
    "Requirement",
    "RequirementDisposition",
    "SourceRights",
    "Split",
    "TaskManifest",
    "TaskType",
    "UseCaseSource",
    "Visibility",
    "candidate_source_hash",
]
